### PR TITLE
add kustomize file

### LINKED ISSUE #183: add kustomize file to be deployable as module
Adding a kustomization file would enable the deployment to be consumed as "kustomization module".
 A very light weight one is by no means any stance for or against any specific deployment mode, it just enables this kind of consumption.

This consumption in a _kustomization.yaml_ is what I'm aiming for:
```
resorces:
  - gitub.com/mongodb/mongodb-kuberentes-operator/deploy?ref=master
```

### PR DESCRIPTION
**Pull request by blaggacao**
### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

closes #183

### CODE REVIEW

**Review by chatton — COMMENTED** [review]
Hi @blaggacao this looks great, thanks for the contribution!

Placing this file directly in the deploy directory will make a regular `kubectl apply -f deploy` result in the following error

```bash
error: unable to recognize "deploy/kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
```

I don't have a lot of experience with `kustomize`, but it looks like we generally have the kustomize file at the top level of a directory, and then have all the yaml files in sub directories underneath that.

perhaps we could move the current contents of deploy to deploy/operator or similar, and end up with a directory structure like

```deploy/
├── crds
│   ├── arbitrary_statefulset_configuration
│   │   └── mongodb.com_v1_custom_volume_cr.yaml
│   ├── mongodb.com_mongodb_crd.yaml
│   ├── mongodb.com_v1_mongodb_cr.yaml
│   ├── mongodb.com_v1_mongodb_openshift_cr.yaml
│   ├── mongodb.com_v1_mongodb_scram_cr.yaml
│   └── mongodb.com_v1_mongodb_tls_cr.yaml
├── kustomization.yaml
├── operator
│   ├── operator.yaml
│   ├── operator_openshift.yaml
│   ├── role.yaml
│   ├── role_binding.yaml
│   └── service_account.yaml
└── testrunner
    ├── cluster_role_binding.yaml
    ├── role.yaml
    ├── role_binding.yaml
    └── service_account.yaml
```

What do you think @rodrigovalin?

one thing to keep in mind also is that a change in this directory structure will also require changes [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/ab14dc5b84348f9fff52a686cc5c56e100f115dd/cmd/testrunner/main.go#L46) for our e2e tests to use the correct deployment

**Comment by blaggacao** [comment]
> Placing this file directly in the deploy directory will make a regular kubectl apply -f deploy result in the following error

Oh sorry! &mdash; not my style, usually.


> but it looks like we generally have the kustomize file at the top level of a directory, and then have all the yaml files in sub directories underneath that.

That's the correct approach, I'll amend the PR, shortly.

**Comment by rodrigovalin** [comment]
Hello @blaggacao. One of the test is broken with: `cmd/testrunner/crds/crds.go:8:2: imported and not used: "path"`. We should be ready to go once that is fixed. Thanks

**Comment by blaggacao** [comment]
> Hello @blaggacao. One of the test is broken with: `cmd/testrunner/crds/crds.go:8:2: imported and not used: "path"`. We should be ready to go once that is fixed. Thanks

Oh, sorry fr the oversight. Just force-pushed a fix upon latest commit.

**Comment by chatton** [comment]
@blaggacao  it looks you haven't signed the CLA yet, could you double check that you've done that please? Thanks!

**Comment by blaggacao** [comment]
@chatyon IIRC an email was never recived. Will check spam, and report back. :+1:

**Comment by blaggacao** [comment]
@chatton Can you check what's failing, evergreen seems to be locked away behind some mongo corporate login.

**Comment by blaggacao** [comment]
I rebased on master

**Review by chatton — COMMENTED** [review]
Hi @blaggacao , it looks like there is one missing updated reference, the e2e test deploys the operator using this script https://github.com/mongodb/mongodb-kubernetes-operator/blob/d93a7bc59a9fe226a527d8a6cc53223e5388678f/scripts/dev/build_and_deploy_operator.py#L30

so we will need to make sure all these new file paths are correct

**Comment by blaggacao** [comment]
@chatton Thanks I forced push a presumed fix.

**Comment by chatton** [comment]
Hi @blaggacao sorry for the late reply, I had meant that we use the python script I linked to start the end to end tests (which read those resources based on file path) so you'll need to also update those paths for the tests to deploy the correct resources

**Comment by chatton** [comment]
Hi @blaggacao it looks like there is just one more issue. It appears as though there is no nice way to configure the operator-sdk testing tool to specify the deploy directory (it always looks in `deploy`). As a result of this the tests are unable to find the file there. I think what we can do here for now is to move these files in the e2e testing image.

We can add the following line to the [this Dockerfile template](https://github.com/mongodb/mongodb-kubernetes-operator/blob/f964d091bce75db3fe2f486c23aadb8295ec817e/scripts/dev/templates/Dockerfile.e2e#L3)

```bash
# Operator SDK expects all deployment files to exist in the deploy directory
RUN mv deploy/operator/* deploy/
```

above the block command

**Comment by bznein** [comment]
Hi @blaggacao, just a little update:

To make it work, you can add the lines @chatton suggested, but instead of adding them before the block command, you will have to add them inside them:

```
{% extends "Dockerfile.template" %}


{% block command -%}
# Operator SDK expects all deployment files to exist in the deploy directory
RUN mv deploy/operator/* deploy/
CMD ["/bin/operator-sdk", "test", "local",  "./test/e2e",  "--namespace", "default", "--verbose", "--kubeconfig", "/etc/config/kubeconfig" ]
{% endblock -%}
```

**Comment by chatton** [comment]
closing this PR - changes introduced in #240

**Comment by blaggacao** [comment]
@chatton Thank you so much! I was in another rabbit hole at the moment.

**Pull request closed without merging**
