### PR TITLE
Feature cluster wide operator reorg

### PR DESCRIPTION
**Pull request by bugslifesolutions**
### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you signed all of your commits?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by haslersn** [comment]
It seems this also fixes #834

**Comment by bugslifesolutions** [comment]
@priyolahiri , @haslersn , @rodrigovalin and @jasonmimick; Thank you for your help with this PR.  I'd like to contribute more efficiently and welcome your feedback/suggestions. 
Sorry for the back pull merge commit.  Was trying to keep up to date with my working version (that includes this pull request) and didn't realize the push to bugslifesolutions/mongodb-kubernetes-operator would impact this pull request... thanks again for your patience.

**Comment by bznein** [comment]
Hi @bugslifesolutions,

thanks for all this work. 

I see two failures: on the `Kube-linter check` you will need to modify the file `.github/workflows/kubelinter-check.yml` to make sure it now points to the correct directories since files have been moved around.

I'm not sure about the `Lint-code base` check... I see that @rodrigovalin in one of the commits of #824 has updated Super-Linter while facing the same issue, so you might want to merge master again to make sure the test passes.

**Comment by priyolahiri** [comment]
@bugslifesolutions can you please rebase on master so that the failing tests are fixed and the conflicts are resolved?

**Comment by bugslifesolutions** [comment]
Will do.

**Comment by bugslifesolutions** [comment]
Opening a cleaner PR rebased on master.

**Pull request closed without merging**
