### PR TITLE
feat: set ns connectionStringSecret per user

### PR DESCRIPTION
**Pull request by aexei**
### All Submissions:

* [X] Have you opened an Issue before filing this PR?
* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [X] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by aexei** [comment]
Closes #1409

**Comment by irajdeep** [comment]
Hi - thanks for the PR. If you noting the operator build task it's failing with this error:
```
github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578\n#14 33.46 # github.com/mongodb/mongodb-kubernetes-operator/api/v1\n#14 33.46 api/v1/mongodbcommunity_types.go:782:4: unknown field ConnectionStringSecretNamespace in struct literal of type
```

**Comment by irajdeep** [comment]
Hi aexei, Since you haven't gotten back to this - I have cherry-picked your commit into this: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1463 and will work on adding this feature. (I have added you as a co-author)

**Comment by aexei** [comment]
Thank you! Sorry for the delay, I missed the automated message.


> Hi aexei, Since you haven't gotten back to this - I have cherry-picked your commit into this: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1463 and will work on adding this feature. (I have added you as a co-author)

**Pull request closed without merging**
