### PR TITLE
Made operator resources configurable in helm-chart

### LINKED ISSUE #703: Resource request and limits not configurable in helmchart
I've installed the operator via the helm-chart and found out that the resource requirements are not controlled via the values.yaml but 'hard-coded' in the operator deployment.

These resource requirements are quite huge, especially when trying to install the operator on a smaller cluster.

Now defaulting to:
```
resources:
  limits:
    cpu: 1100m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 200Mi
```

These should be configurable through settings in the values.yaml.

### PR DESCRIPTION
**Pull request by freerk**
Closes #703

### CODE REVIEW

**Comment by rodrigovalin** [comment]
Hello @freerk  and thanks for your contribution.

Please make sure you sign the [Contributors Agreement](https://www.mongodb.com/legal/contributor-agreement) so we can proceed.

**Comment by freerk** [comment]
Hi.
I already signed the agreement 

Freerk

**Review by rodrigovalin — COMMENTED** [review]
@freerk can you make sure the default resources we currentlu have, are moved to the Helm chart `values.yaml`, instead of having an empty dictionary in there.

**Review by priyolahiri — APPROVED** [review]

**Comment by priyolahiri** [comment]
@freerk Your commits need to be signed. Please follow the guide here: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by freerk** [comment]
Done.

**Review by Starefossen — APPROVED** [review]

**Pull request closed without merging**
