### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StMarian**
Fix license link

### All Submissions:

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Comment by chatton** [comment]
Hi @steveren thanks for the contribution! It looks the CLA hasn't been signed yet, you'll need to double check this before we can merge your update!

**Comment by chatton** [comment]
@StMarian  thanks for the contribution! It looks the CLA hasn't been signed yet, you'll need to double check this before we can merge your update!

**Comment by StMarian** [comment]
Glad to help :)
Probably did a mistake when was signing it initially. Re-signed.

**Comment by chatton** [comment]
Thanks @StMarian

**Pull request merged**
