### PR TITLE
CLOUDP-65312: arbitrary statefulset configuration

### LINKED ISSUE #61: storageClassName missing in the CRD
Hello,

How can we specify the `storageClassName` for the `sts` getting created by the operator? 

In the [example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_cr.yaml) and in the [crd definition](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_mongodb_crd.yaml) I do not see any place where to set it up.

### PR DESCRIPTION
**Pull request by bznein**
WIP until I verify that the tests run fine on evg as well, then ready for review

After investigation and tries, I decided to proceed with the same logic used in the enterprise operator for merging specs, as it seems the most reliable and clear.

Unit tests are, as well, taken from the enterprise operator.

More e2e tests are most likely wanted, but outside the scope of this PR. Will open a ticket to track this if we think it would be a good idea.

## All Submissions:

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
 
closes #61

### CODE REVIEW

**Comment by bznein** [comment]
Issue WIP until we figure out issues with evergreen e2e tests

**Comment by rodrigovalin** [comment]
@fabianlindfors can you make sure the tests run please?

**Comment by bznein** [comment]
evergreen retry

**Comment by bznein** [comment]
evergreen retry

**Comment by bznein** [comment]
evergreen retry

**Comment by bznein** [comment]
evergreen retry

**Comment by bznein** [comment]
evergreen retry

**Pull request merged**
