### PR TITLE
Set Agent HealthStatus file path variable scope to public to be used in enterprise

### PR DESCRIPTION
**Pull request by irajdeep**
### All Submissions:

* [ ] Have you opened an Issue before filing this PR?
* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by lsierant — APPROVED** [review]
LGTM!

**Review by mircea-cosbuc — APPROVED** [review]

**Comment by slaskawi** [comment]
LGTM

**Comment by slaskawi** [comment]
@irajdeep Since we'll be removing the Go-based diagnostic tool, do we still need this?

**Comment by irajdeep** [comment]
This can be closed; thanks for the follow-up reminder.

**Pull request closed without merging**
