### PR TITLE
(DOCSP-16543): Changed MongoDB resource to MongoDBCommunity resource.

### PR DESCRIPTION
**Pull request by corryroot**
@rodrigovalin, I updated "MongoDB resource" to " MongoDBCommunity resource".

[JIRA](https://jira.mongodb.org/browse/DOCSP-16543
)
### All Submissions:

* [ ] Have you opened an Issue before filing this PR?
* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by jwilliams-mongo — COMMENTED** [review]
@corryroot your changes LGTM, but I have a question about links: in markdown the link target is derived from each heading title. I see that you updated some of the link titles -- did you also update the links that point to these headings?

I think a quick search of `#*mongodb*` would find all links that contain the old string in the repo.

**Comment by corryroot** [comment]
> @corryroot your changes LGTM, but I have a question about links: in markdown the link target is derived from each heading title. I see that you updated some of the link titles -- did you also update the links that point to these headings?
> 
> I think a quick search of `#*mongodb*` would find all links that contain the old string in the repo.

Thanks @jwilliams-mongo! I updated "MongoDB resource" to "MongoDBCommunity" resources in BOTH the link text within the brackets AND the page or section titles themselves. Is that what you're verifying?

**Comment by jwilliams-mongo** [comment]
> 

@corryroot Take this for example:

https://github.com/mongodb/mongodb-kubernetes-operator/pull/859/files#diff-c8d6bd2a8c7cac9bb817cbe6a434964ff042aecc2ce452e6d876cc68d75ba0a7R5

Because the title of this section has changed to "Secure MongoDBCommunity Resource Connections using TLS", the link target in the line above would change to `#secure-mongodbcommunity-resource-connections-using-tls`.

**Review by jwilliams-mongo — APPROVED** [review]
@corryroot LGTM! thanks for addressing my comments

**Review by rodrigovalin — APPROVED** [review]
LGTM

**Pull request merged**
