### PR TITLE
Reorg to simplify cluster-wide operator deployment

### PR DESCRIPTION
**Pull request by bugslifesolutions**
- moving/renaming mostly
- cluster wide manager patch
- separation of singleNamespace vs clusterwide RBAC

### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you signed all of your commits?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by rodrigovalin** [comment]
Hello @bugslifesolutions 

Thanks for contributing this patch. Before we can proceed with reviewing it, can you please make sure it is rebased on master?

As you can see from the "Files changed", there are many changes that are not part of your work that are being shown. I think rebasing this interactively will allow you to `drop` the commits you don't need. Then you could rebase on master to leave your changes on top of the master history.

I've done this [here](https://github.com/rodrigovalin/mongodb-kubernetes-operator/tree/featureMultiNamespaceOperatorConfiguration), but I can't push to your branch of course. If you want, you can add my fork as a remote and reset your branch from there:

```
git remote add git@github.com:rodrigovalin/mongodb-kubernetes-operator.git
git reset --hard rodrigovalin/featureMultiNamespaceOperatorConfiguration
```

That will make your branch up to date to my rebase on master with no duplicate commits.

After this you can push to your branch the usual way:

```
git push --force-with-lease bugslifesolutions featureMultiNamespaceOperatorConfiguration:featureMultiNamespaceOperatorConfiguration
```

**Review by jasonmimick — APPROVED** [review]

**Review by rodrigovalin — CHANGES_REQUESTED** [review]
Please apply the changes requested; we can't merge the patch in the way it is right now.

Let us know if you need more support on how to do this.

**Comment by bugslifesolutions** [comment]
Sorry for the late reply.  I'll review and resubmit as soon as possible.

**Comment by bugslifesolutions** [comment]
Closing this pull in favor of https://github.com/mongodb/mongodb-kubernetes-operator/pull/820

**Comment by bugslifesolutions** [comment]
Thank you @rodrigovalin  and @jasonmimick for your patience.

**Pull request closed without merging**
