### PR TITLE
Make automation agent log level configurable

### LINKED ISSUE #1226: automation-agent-verbose.log: No space left on device
**What did you do to encounter the bug?**
Just install mongo (3 replicas) with 4Gi disks for logs.

**What did you expect?**
I did not except to see such message.

**What happened instead?**
A lot of such messages in `mongodb-agent` container:
```
Logging error occurred: rolling_file_appender: Failed to write to /var/log/mongodb-mms-automation/automation-agent-verbose.log: write /var/log/mongodb-mms-automation/automation-agent-verbose.log: no space left on device
```

**Screenshots**
Screenshot 2023-02-10 at 15 22 56

**Operator Information**
 - Operator Version (`0.7.8`)
 - MongoDB Image used
   - `docker.io/mongo:5.0.13`
   - `quay.io/mongodb/mongodb-agent:12.0.15.7646-1`

**Kubernetes Cluster Information**
 - Distribution (`AWS EKS`)
 - Version (`1.24`)
 - Image Registry location (`quay`)

**Additional context**
I observed that the `agent` write logs to `/var/log/mongodb-mms-automation` folder which is strange in cloud native applications? Should not we put everything as a container output? Do we really need to create disks for logs?

I did not found any way to configure agent for disabling `DEBUG`. I can overwrite the command, but... I don't think it is a good idea? Any thoughts? Thanks!

### PR DESCRIPTION
**Pull request by p-kimberley**
Closes #1226 

As per the related issue, the default `mongodb-agent` log level is `DEBUG`. This causes a large volume of log entries to be produced and depending on PVC limits, can result in volume exhaustion. Once the log volume is exhausted, `mongodb-agent` emits frequent (several times per second) log messages to stdout, which can cause issues with downstream log collectors.

This PR changes the default MongoDB automation agent log level to `INFO` and adds an option `MongoDBCommunity.spec.agent.logLevel` to enable customisation.

### All Submissions:

* [X] Have you opened an Issue before filing this PR?
* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [X] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by marandalucas** [comment]
@p-kimberley, Could you also implement the rotation policy?

`-maxLogFileDurationHrs 24`

Thanks in advance

**Comment by irajdeep** [comment]
@p-kimberley, thanks for the patch - could you please look into the failing unit test?

**Comment by Dranaxele** [comment]
@p-kimberley, could you have the `-maxLogFiles` option configurable too?

And thanks for your job!

**Comment by irajdeep** [comment]
> Please note, I have been unable to build the image locally due to issues with sonar. If you can point out what I'm doing wrong, that'd be appreciated.

@p-kimberley Are you using a local registry for the image? For dev/test we suggest spinning up a local kind cluster with local registry - which can be spun up with this [script](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/scripts/dev/setup_kind_cluster.sh). And then you can configure both sonar and the e2e workflow to use this kind cluster and registry by configuring the [developer context file](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/contributing.md?plain=1#L49). Let me know if this helps.

**Comment by p-kimberley** [comment]
> @p-kimberley Are you using a local registry for the image? For dev/test we suggest spinning up a local kind cluster with local registry - which can be spun up with this [script](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/scripts/dev/setup_kind_cluster.sh). And then you can configure both sonar and the e2e workflow to use this kind cluster and registry by configuring the [developer context file](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/contributing.md?plain=1#L49). Let me know if this helps.

@irajdeep Yes, I'm running a `kind` dev cluster and a local registry at: `http://localhost:5000` (created using the shell script you mentioned).

`repo_url` in `config.yaml` is set to `localhost:5000`. I can `curl http://localhost:5000/v2/_catalog`, so I know the registry is working.

System specs:
1. Ubuntu 22.01
2. Python 3.8.16 (built from source)

My build steps:
```bash
python3.8 -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip setuptools wheel
python -m pip install -r requirements.txt
make
make all-images deploy
```

Btw - I'm not seeing any images in the local registry at any stage. Should `sonar-docker-build-xxx:latest` be there? If so - perhaps there's a step I'm missing?

**Comment by irajdeep** [comment]
@p-kimberley interesting. The only difference I notice is that I have `Python 3.10.9` locally. 

In the logs you shared, I noticed **python3.10**
```
File "/home/peter/GolandProjects/mongodb-kubernetes-operator/venv/lib/python3.10/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

but in the build steps `python3.8 -m venv venv` you're creating the vritualenvironment with **Python3.8** - wondering why that discrepancy. It seems the virtual environment is not configured properly.

**Comment by irajdeep** [comment]
Are you able to manually `docker build` and `docker push` any image to the `localhost:5000` registry?  

At this point, it's unclear to me why this could be happening; we could try 2 options here: 
1.  Recreate the Kind cluster and the registry - make sure to delete the running containers for the registry before recreating.
2. If you're able to manually push image to the registry, you could manually `docker build/push` the images and do a test.

**Comment by p-kimberley** [comment]
@irajdeep My `config.json` is:
```json
{
    "namespace": "mongodb",
    "repo_url": "http://localhost:5000",
    "operator_image": "mongodb-kubernetes-operator",
    "e2e_image": "community-operator-e2e",
    "version_upgrade_hook_image": "community-operator-version-upgrade-post-start-hook",
    "agent_image_ubuntu": "mongodb-agent-dev",
    "agent_image_ubi": "mongodb-agent-ubi-dev",
    "readiness_probe_image": "mongodb-kubernetes-readiness",
    "s3_bucket": ""
}
```

I'm able to tag+push images to the local registry. After pushing I see the following:
```bash
$ curl http://localhost:5000/v2/_catalog
{"repositories":["registry"]}
```

Should I see at least one `sonar-docker-build-xxx` image name in this response? It looks like the `sonar` Python lib is looking for it, hence the log error:
`docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: sonar-docker-build-2405:latest")`.

I _would_ do as you suggested and build the image manually, however the `sonar-docker-build-xxx` image uses a randomised suffix, so I don't see any way of building and telling the `sonar` Python lib to use that particular image.

Anyway, if we can't resolve these build issues in my env, I'm going to have to leave this PR to the mongo team to test and verify.

It would be nice to have the issue addressed though, as the verbose logging soaks up around 10GB (roughly 1.5GB per day, with 1 week retention). This can catch people off-guard, especially if they don't size their PVs accordingly. Once you breach that limit, as I said in the issue - high volume container log spam occurs.

**Comment by irajdeep** [comment]
The config.json looks good to me. I will test this patch this week and provide an update.

**Review by irajdeep — APPROVED** [review]

**Comment by irajdeep** [comment]
Operator `0.7.9` version has been released today with the fix.

**Comment by schans** [comment]
Thank you!

**Pull request merged**
