### PR TITLE
remove github.com/pkg/errors

### PR DESCRIPTION
**Pull request by fahedouch**
Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>

### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

fixing  https://github.com/mongodb/mongodb-kubernetes-operator/issues/1030
PS: I am using my lovely friend @AkihiroSuda tool https://github.com/AkihiroSuda/go-wrap-to-percent-w

### CODE REVIEW

**Comment by slaskawi** [comment]
Thanks for the Pull Request @fahedouch !

Could you please run `go mod tidy` and make sure the the `github.com/pkg/errors` get dropped. Please commit go mod modifications in a separate commit.

**Comment by fahedouch** [comment]
@slaskawi should I squash my commits :) ?

**Review by slaskawi — APPROVED** [review]
LGTM, could you please rebase it? Once it's green I'll merge it.

**Comment by fahedouch** [comment]
@slaskawi Sorry for the delayed rebase. fixed :)

**Comment by slaskawi** [comment]
Integrated, thanks @fahedouch !

**Pull request merged**
