### PR TITLE
Add field IgnoreUnkownUsers to spec to allow users created outside of the CRD.

### LINKED ISSUE #361: Cannot create Database or collection and authenticate with newly created user from mongo shell
Hi,

We are trying to create a database from mongoshell after successfully logging into the primary Db, Following are the commands.
1. mongo --host <ip> --port 27017 --username <username> --password <password> --authenticationDatabase <dbName>  - With this command we are able to successfully authenticate into a particular database created while deploying theYAML file alongwith the admin database, We are able to create collections add data.
2. But when we try to create a new database after logging in using any other cred like the admin DB creds and execute command in following order
a - use testdb
b - db.createUser(
{
	user: "test",

	pwd: "test",

	roles:[{role: "dbAdmin" , db:"testdb"}],

	mechanisms: ["SCRAM-SHA-256"],
});
c - The user is created successfully, but to create any collection or insert someting in db i need to first authenticate with that use, so when executing below command
d - 
db.auth("test", "test")

Getting the following error - 

Error: Authentication failed.
0

But all this steps work for the Databse and users created from the deployment yaml files in the operator crds.

Please do let me know if any more information needed from my end.

### PR DESCRIPTION
**Pull request by chatton**
### All Submissions:

* [X] Have you opened an Issue before filing this PR?
* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [X] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

closes #361

This pr adds a field `spec.security.authentication.ignoreUnknownUsers` which ensures that it is possible to add users directly to the database without them being removed by the agent through automation.

### CODE REVIEW

**Review by bznein — APPROVED** [review]
LGTM!

**Comment by hayazan** [comment]
I added the ignoreUnknownUsers field, but it still can’t  users created outside of the CRD

**Comment by hayazan** [comment]
image

**Comment by hayazan** [comment]
image

IgnoreUnkownUsers  or ignoreUnknownUsers

**Comment by bznein** [comment]
HI @hayazan, looks like the example contains a typo!
The correct field is `ignoreUnknownUsers`, thanks for noticing!

**Comment by hayazan** [comment]
> HI @hayazan, looks like the example contains a typo!
> The correct field is `ignoreUnknownUsers`, thanks for noticing!
> 
> Does the problem still persist if you use the correct field name? If so, can we move the discussion to the issue? thanks!

Yes, the problem still exists

**Comment by bznein** [comment]
Hi @hayazan,

The new field is not release yet, sorry I should have spotted it before!
Unless you are rebuilding the operator it's normal to still have the issue! We will release the new version soon and you should be able to fix your issue

**Comment by hayazan** [comment]
image
image

Using the latest code deployment, the pod can't get up, prompt nt health file: error opening file: open /healthstatus/agent-health-status.json: no such file or directory

**Comment by bznein** [comment]
Hi @hayazan, that message is expected and should not prevent the pods from getting ready. Can you open a new issue and provide full details of your issue? Thanks

**Comment by hayazan** [comment]
> Hi @hayazan, that message is expected and should not prevent the pods from getting ready. Can you open a new issue and provide full details of your issue? Thanks

IgnoreUnkownUsers Is this problem fixed?

**Comment by bznein** [comment]
As per release notes: https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.5.2 the issue is fixed and released.

If you have any other queries please feel free to open a new issue

Thanks

**Pull request merged**
