### PR TITLE
Release MongoDB Kubernetes Operator v0.7.7

### PR DESCRIPTION
**Pull request by mircea-cosbuc**
### All Submissions:

* [ ] Have you opened an Issue before filing this PR?
* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by irajdeep — APPROVED** [review]

**Comment by martinkroupa** [comment]
Hi, I noticed that the image quay.io/mongodb/mongodb-kubernetes-operator:0.7.6 is still in [manager.yaml](https://github.com/mongodb/mongodb-kubernetes-operator/blob/v0.7.7/config/manager/manager.yaml#L57) and [operator_openshift.yaml](https://github.com/mongodb/mongodb-kubernetes-operator/blob/v0.7.7/deploy/openshift/operator_openshift.yaml#L59).
Is there a reason for this, or has the change been forgotten?

**Comment by mircea-cosbuc** [comment]
@martinkroupa The change was wrongfully omitted during the release. Fixing this with a new release and a mention in the release notes for 0.7.7 about the omission.

**Comment by martinkroupa** [comment]
@mircea-cosbuc Thank you for the fix in release 0.7.8. Have a nice day.

**Comment by dosmanak** [comment]
Hello, I just checked the repo for new versions and have found the 0.7.8 is pretty old while 0.7.7 and 0.7.6 are build recently. And also the 0.7.8 in quay.io has reported some vulnerabilities. It seems the the pipeline is still not fully fixed. 
@mircea-cosbuc could you please check it?

**Comment by mircea-cosbuc** [comment]
@dosmanak Thank you for the heads up, this was an omission in our daily rebuilds. It should be included in the next daily rebuilds.

**Pull request merged**
